name       : xorg-driver-video-openchrome
version    : 0.6.0
release    : 7
source     :
    - https://www.x.org/archive/individual/driver/xf86-video-openchrome-0.6.0.tar.bz2 : da2975c6379358de52c1257710c67eb59139a7f0a1cd28d00cc64cc3e1c02f75
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : OpenChrome Video Driver
description: |
    The Xorg OpenChrome Driver package contains the X.Org Video Driver for Via integrated video cards including Unichrome, Unichrome Pro and Chrome9 series.
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xext)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
    - pkgconfig(xvmc)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Blank dir
    rm -rf $installdir/usr/sbin
